# Generated by roxytest: do not edit by hand!

# File R/fn_get.R: @tests

test_that("Function get_fam_children() @ L78", {
  expect_equal(get_fam_children(test_ged(), "@F1@"), "@I1@")
  expect_equal(get_fam_children(test_ged(), "@F1@", "BIRTH"), "@I1@")
  expect_equal(get_fam_children(test_ged(), "@F2@"), c("@I5@", "@I6@"))
})


test_that("Function get_indi_partners() @ L119", {
  expect_equal(get_indi_partners(test_ged(), "@I1@"), "@I4@")
  expect_equal(get_indi_partners(test_ged(), "@I4@"), "@I1@")
})


test_that("Function get_indi_children() @ L142", {
  expect_equal(get_indi_children(test_ged(), "@I1@"), c("@I5@", "@I6@"))
  expect_equal(get_indi_children(test_ged(), "@I4@"), c("@I5@", "@I6@"))
  expect_equal(get_indi_children(test_ged(), "@I2@"), "@I1@")
})


test_that("Function get_indi_parents() @ L168", {
  expect_equal(get_indi_parents(test_ged(), "@I1@"), c("@I2@", "@I3@"))
  expect_equal(get_indi_parents(test_ged(), "@I5@"), c("@I1@", "@I4@"))
  expect_equal(get_indi_parents(test_ged(), "@I6@"), c("@I1@", "@I4@"))
  expect_equal(get_indi_parents(test_ged(), "@I2@"), character())
})


test_that("Function get_indi_mothers() @ L192", {
  expect_equal(get_indi_mothers(test_ged(), "@I1@"), "@I3@")
})


test_that("Function get_indi_fathers() @ L207", {
  expect_equal(get_indi_fathers(test_ged(), "@I1@"), "@I2@")
})


test_that("Function get_indi_siblings() @ L247", {
  expect_equal(get_indi_siblings(test_ged(), "@I1@"), character())
  expect_equal(get_indi_siblings(test_ged(), "@I5@"), "@I6@")
  expect_equal(get_indi_siblings(test_ged(), "@I6@"), "@I5@")
  expect_equal(get_indi_siblings(test_ged(), "@I6@", inc_half = TRUE), "@I5@")
})


test_that("Function get_unused_recs() @ L371", {
  expect_equal(get_unused_recs(test_ged()), c("@U2@","@F3@","@N1@"))
})


test_that("Function get_descendants() @ L408", {
  expect_equal(sort(get_descendants(test_ged(), "@I2@")), 
               c("@I1@", "@I5@", "@I6@"))
  expect_equal(sort(get_descendants(test_ged(), "@I2@", 
                                    inc_indi = TRUE)), 
               c("@I1@", "@I2@" ,"@I5@", "@I6@"))
  expect_equal(sort(get_descendants(test_ged(), "@I2@", 
                                    inc_part = TRUE)), 
               c("@I1@", "@I3@", "@I4@", "@I5@", "@I6@"))
  expect_equal(sort(get_descendants(test_ged(), "@I2@", 
                                    inc_fam = TRUE)), 
               c("@F1@", "@F2@", "@I1@", "@I5@", "@I6@"))
})


test_that("Function get_ancestors() @ L482", {
  expect_equal(sort(get_ancestors(test_ged(), "@I5@")),
               c("@I1@","@I2@","@I3@","@I4@"))
  expect_equal(sort(get_ancestors(test_ged(), "@I5@", inc_indi = TRUE)),
               c("@I1@","@I2@","@I3@","@I4@","@I5@"))
  expect_equal(sort(get_ancestors(test_ged(), "@I5@", inc_sibs = TRUE)),
               c("@I1@","@I2@","@I3@","@I4@"))
  expect_equal(sort(get_ancestors(test_ged(), "@I5@", 
                                  inc_indi = TRUE,
                                  inc_sibs = TRUE)),
               c("@I1@","@I2@","@I3@","@I4@","@I5@","@I6@"))
  expect_equal(sort(get_ancestors(test_ged(), "@I5@", inc_fam = TRUE)),
               c("@F1@","@F2@","@I1@","@I2@","@I3@","@I4@"))
})


test_that("Function get_records_by_pattern() @ L547", {
  expect_equal(get_records_by_pattern(test_ged(), "California"), "@I1@")
  expect_equal(get_records_by_pattern(test_ged(), "Mother"), "@I3@")
  expect_equal(get_records_by_pattern(test_ged(), "Mother", TRUE), 
               list("@I3@" = "1 NAME Mother /Bloggs/"))
})

