# Generated by roxytest: do not edit by hand!

# File R/io_import.R: @tests

test_that("Function read_gedcom() @ L17", {
  maximal <- test_path("maximal70.ged")
  maximal <- withr::local_tempfile(lines = fix_maximal_header(maximal), 
                                   fileext = ".ged")
  length_maximal <- length(readLines(maximal))
  ged <- read_gedcom(maximal)
  expect_equal(length(ged@c_as_ged), length_maximal)
})

