# Generated by roxytest: do not edit by hand!

# File R/cls_note.R: @tests

test_that("Function class_note() @ L47", {
  expect_error(class_note(), regexp = "@text has too few elements")
  expect_error(class_note(letters[1:2]), regexp = "@text has too many elements")
  expect_snapshot_value(class_note("test")@as_ged, "json2")
  expect_snapshot_value(class_note("test", language = "en")@as_ged, "json2")
  expect_snapshot_value(class_note("test", 
                                   language = "en",
                                   translations = class_translation_txt("test",
                                                                    language = "en"))@as_ged, "json2")
  expect_snapshot_value(class_note("test", 
                                   language = "en",
                                   translations = list(class_translation_txt("test",
                                                                    language = "en"),
                                                   class_translation_txt("test2",
                                                                    language = "en")))@as_ged, "json2")
  expect_snapshot_value(class_note("test", 
                                   citations = class_citation("@S1@", 
                                                              notes = class_note("note text 2", 
                                                                                 citations = class_citation("@S4@"))))@as_ged, 
                       "json2")
  expect_error(class_note("test", 
                          language = "en",
                          translations = class_address("street"))@as_ged,
               regexp = "@translations must be <list> or <gedcomS7::class_translation_txt>")
  expect_error(class_note("test", 
                          language = "en",
                          translations = list(class_translation_txt("test",
                                                                language = "en"),
                                          class_address("street"))),
               regexp = "@translations contains an invalid object not of class_translation_txt")
})

