# Generated by roxytest: do not edit by hand!

# File R/cls_fact_fam.R: @tests

test_that("Function class_event_fam() @ L72", {
  expect_error(class_event_fam("marr", fact_val = "Y"), 
               regexp = "@fact_type has an invalid value")
  expect_error(class_event_fam("MARR", fact_val = "Yes"), 
               regexp = "@fact_val has an invalid value")
  expect_error(class_event_fam("EVEN", fact_desc = "Fact desc"), 
               regexp = "@fact_val has too few elements")       
  expect_error(class_event_fam("DIV", fact_val = "Y", husb_age = "73"), regexp = "@husb_age is in an invalid format")
  expect_snapshot_value(class_event_fam("DIV", fact_val = "Y")@as_ged, "json2")
  expect_snapshot_value(class_event_fam("DIV", fact_val = "Y", wife_age_phrase = "old")@as_ged, "json2")
  expect_snapshot_value(class_event_fam("DIV", fact_val = "Y", husb_age = "73y 4m",
                                        wife_age = "60y")@as_ged, "json2")
})


test_that("Function class_attr_fam() @ L102", {
  expect_error(class_attr_fam("residence", fact_val = "Earth"), 
               regexp = "@fact_type has an invalid value")
  expect_error(class_attr_fam("RESI", fact_val = ""), 
               regexp = "@fact_val has too few characters")   
  expect_error(class_attr_fam("FACT"), regexp = "@fact_desc has too few elements")
})

