# Generated by roxytest: do not edit by hand!

# File R/cls_validators.R: @tests

test_that("Function chk_input_size() @ L35", {
  expect_equal(chk_input_size(letters, "x", min_len = 27),
                              "x has too few elements. The minimum is 27.")
  expect_equal(chk_input_size(1:4, "y", max_len = 3),
                              "y has too many elements. The maximum is 3.")
  expect_equal(chk_input_size(c("hello","once again"), "z", min_val = 6),
                              "z has too few characters. The minimum is 6.")
  expect_equal(chk_input_size(c("goodbye","to you"), "a", max_val = 6),
                              "a has too many characters. The maximum is 6.")
  expect_equal(chk_input_size(18:36, "b", min_val = 19),
                              "b has a value which is too low. The minimum is 19.")
  expect_equal(chk_input_size(2:9, "c", max_val = 8),
                              "c has a value which is too high. The maximum is 8.")
  expect_null(chk_input_size(letters, "", min_len = 26))
  expect_null(chk_input_size(letters, "", max_len = 26))
  expect_null(chk_input_size(month.abb, "", min_val = 3))
  expect_null(chk_input_size(month.abb, "", max_val = 3))
  expect_null(chk_input_size(20:40, "", min_val = 20))
  expect_null(chk_input_size(20:40, "", max_val = 40))
})


test_that("Function chk_input_pattern() @ L77", {
  expect_equal(chk_input_pattern(letters, "x", "[a-y]"),
               "x is in an invalid format: z")
  expect_equal(chk_input_pattern(month.abb, "y", "[A-Z][a-z][abe-z]"),
               "y is in an invalid format: Dec")
  expect_equal(chk_input_pattern(month.abb, "z", "[A-Z][a-z][a-xz]"),
               "z is in an invalid format: May")
})


test_that("Function chk_input_choice() @ L101", {
  expect_match(chk_input_choice(month.abb, "a", month.abb[-6]),
               "^a has an invalid value: Jun")
  expect_match(chk_input_choice(letters, "b", letters[-16]),
               "^b has an invalid value: p")
  expect_match(chk_input_choice(LETTERS, "c", LETTERS[-20]),
               "^c has an invalid value: T")
})


test_that("Function chk_input_date_cpts() @ L159", {
  expect_equal(chk_input_date_cpts(numeric(),1,2),
               "Year must be defined")
  expect_equal(chk_input_date_cpts(2000,1,2, bce = TRUE),
               "BCE date must contain year only")
  expect_equal(chk_input_date_cpts(2000,numeric(),2),
               "Day is defined without a month")
  expect_equal(chk_input_date_cpts(2000,13,2),
               "Invalid date")
  expect_equal(chk_input_date_cpts(2001,2,29),
               "Invalid date")
  expect_null(chk_input_date_cpts(2000,2,29))
  expect_null(chk_input_date_cpts(2020,6,14))
  expect_null(chk_input_date_cpts(1980,9,3))
})


test_that("Function chk_input_dates() @ L194", {
  expect_null(chk_input_dates(NULL,NULL))
  expect_null(chk_input_dates("2002-09-08",NULL))
  expect_equal(chk_input_dates(Sys.Date(), Sys.Date()),
               "Start date is the same as end date")
})


test_that("Function chk_whole_number() @ L243", {
  expect_equal(chk_whole_number(1.1, "a"),
               "a must be a whole number")
  expect_equal(chk_whole_number(4.2, "b"),
               "b must be a whole number")
  expect_null(chk_whole_number(1:4, ""))
  expect_null(chk_whole_number(5, ""))
})


test_that("Function chk_input_parents() @ L264", {
  expect_null(chk_input_parents(character(), "@child", character(), "@parent"))
  expect_null(chk_input_parents(character(), "@child", "parent", "@parent"))
  expect_equal(chk_input_parents("child", "@child", character(), "@parent"),
               "@child requires a @parent")
  expect_null(chk_input_parents("child", "@child", "parent", "@parent"))
})

