# Generated by roxytest: do not edit by hand!

# File R/fn_is.R: @tests

test_that("Function get_record_type() @ L33", {
  expect_error(get_record_type(1), regexp = "Unrecognised record")
  expect_equal(get_record_type(IndividualRecord()), "INDI")
  expect_equal(get_record_type(FamilyRecord()), "FAM")
  expect_equal(get_record_type(SourceRecord()), "SOUR")
  expect_equal(get_record_type(RepositoryRecord(repo_name = "Lib")), "REPO")
  expect_equal(get_record_type(SubmitterRecord(subm_name = "subm")), "SUBM")
  expect_equal(get_record_type(NoteRecord(text = "text")), "SNOTE")
  expect_equal(get_record_type(MediaRecord(files = MediaFile("file.ext", media_type = "type"))), "OBJE")
})

