# Generated by roxytest: do not edit by hand!

# File R/cls_citation.R: @tests

test_that("Function class_citation() @ L43", {
  expect_snapshot_value(class_citation()@c_as_ged, "json2")
  expect_error(class_citation("@1@",
                              fact_phrase = "phrase"),
               regexp = "@fact_phrase requires a @fact_type")
  expect_error(class_citation("@1@",
                              role = "HUSB"),
               regexp = "@role requires a @fact_type")
  expect_error(class_citation("@1@",
                              fact_type = "BIRT", role_phrase = "phrase"),
               regexp = "@role_phrase requires a @role")
  expect_error(class_citation("@1@",
                              certainty = "4"),
               regexp = "@certainty has an invalid value")
  expect_error(class_citation("@1@",
                              notes = ""),
               regexp = "@notes is in an invalid format")
  expect_error(class_citation("@1@",
                              fact_type = "birth"),
               regexp = "@fact_type has an invalid value")             
  expect_snapshot_value(class_citation("@1@",
                                       where = "page 2",
                                       date = "2 JUN 2006",
                                       source_text = c("verbatim","text"),
                                       fact_type = "BIRT",
                                       fact_phrase = "Parish births",
                                       role = "HUSB",
                                       role_phrase = "phrase",
                                       certainty = "3",
                                       media_links = class_media_link("@34E@"),
                                       note_xrefs = c("@WER@",
                                                     "@4334@"),
                                       notes = c("these are","some notes"))@c_as_ged, "json2")
})

