# Generated by roxytest: do not edit by hand!

# File R/cls_family_link.R: @tests

test_that("Function FamilyLinkSpouse() @ L23", {
  expect_error(FamilyLinkSpouse(), regexp = "@fam_xref has too few elements")
  expect_snapshot_value(FamilyLinkSpouse("@F123@")@GEDCOM, "json2")
  expect_snapshot_value(FamilyLinkSpouse("@F2@", 
                                                 notes = list(Note("test")))@GEDCOM, "json2")
})


test_that("Function FamilyLinkChild() @ L68", {
  expect_error(FamilyLinkChild("@F123@", pedigree = "father"), 
                                       regexp = "@pedigree has an invalid value")
  expect_error(FamilyLinkChild("@F123@", pedigree = "OTHER"), 
                                       regexp = "A @pedigree_phrase must be given if @pedigree is 'OTHER'")
  expect_error(FamilyLinkChild("@F123@", confidence = "LOW"), 
                                       regexp = "@confidence has an invalid value")  
  expect_error(FamilyLinkChild("@F123@", confidence_phrase = "Don't know"), 
                                       regexp = "@confidence_phrase requires a @confidence")                                  
  expect_snapshot_value(FamilyLinkChild("@F2@", 
                                                 pedigree = "ADOPTED",
                                                 pedigree_phrase = "By people",
                                                 confidence = "CHALLENGED",
                                                 confidence_phrase = "By someone",
                                                 note_xrefs = c("@242@","@GJFJ@"))@GEDCOM, "json2")
})

