# Generated by roxytest: Do not edit by hand!

# File R/"04_locations.R": @tests

test_that("[unknown alias] @ L34", {
  expect_error(class_place())
  expect_error(class_place(""))
  expect_snapshot_value(class_place("here"), "serialize")
})

