# Generated by roxytest: do not edit by hand!

# File R/cls_note.R: @tests

test_that("Function class_note() @ L41", {
  expect_error(class_note(), regexp = "@text has too few elements")
  expect_error(class_note(letters[1:2]), regexp = "@text has too many elements")
  expect_snapshot_value(class_note("test")@as_ged, "json2")
  expect_snapshot_value(class_note("test", language = "en")@as_ged, "json2")
  expect_snapshot_value(class_note("test", 
                                   language = "en",
                                   alt_text = class_translation_txt("test",
                                                                    language = "en"))@as_ged, "json2")
  expect_snapshot_value(class_note("test", 
                                   language = "en",
                                   alt_text = list(class_translation_txt("test",
                                                                    language = "en"),
                                                   class_translation_txt("test2",
                                                                    language = "en")))@as_ged, "json2")
  expect_error(class_note("test", 
                          language = "en",
                          alt_text = class_address("street"))@as_ged,
               regexp = "@alt_text must be <list> or <gedcomS7::class_translation_txt>")
})

