# Generated by roxytest: do not edit by hand!

# File R/cls_family_link.R: @tests

test_that("Function class_spouse_family_link() @ L15", {
  expect_error(class_spouse_family_link(), regexp = "@fam_xref has too few elements")
  expect_snapshot_value(class_spouse_family_link("@F123@")@as_ged, "json2")
  expect_snapshot_value(class_spouse_family_link("@F2@", 
                                                 notes = list(class_note("test")))@as_ged, "json2")
})


test_that("Function class_child_family_link() @ L64", {
  expect_error(class_child_family_link("@F123@", pedigree = "father"), 
                                       regexp = "@pedigree has an invalid value")
  expect_error(class_child_family_link("@F123@", pedigree = "OTHER"), 
                                       regexp = "@pedigree_phrase has too few elements")
  expect_error(class_child_family_link("@F123@", confidence = "LOW"), 
                                       regexp = "@confidence has an invalid value")  
  expect_error(class_child_family_link("@F123@", confidence_phrase = "Don't know"), 
                                       regexp = "@confidence_phrase requires a @confidence")                                  
  expect_snapshot_value(class_child_family_link("@F2@", 
                                                 pedigree = "ADOPTED",
                                                 pedigree_phrase = "By people",
                                                 confidence = "CHALLENGED",
                                                 confidence_phrase = "By someone",
                                                 note_xrefs = c("@242@","@GJFJ@"))@as_ged, "json2")
})

