# Generated by roxytest: do not edit by hand!

# File R/utils_parse.R: @tests

test_that("Function parse_gedcom_date() @ L50", {
  expect_equal(parse_gedcom_date("BEF 1980"), as.Date(NA_character_))
  expect_equal(parse_gedcom_date("TO 23 JUN 2001"), as.Date(NA_character_))
  expect_equal(parse_gedcom_date("AFT 1600", FALSE), as.Date(NA_character_))
  expect_equal(parse_gedcom_date("FROM FEB 1900", FALSE), as.Date(NA_character_))
  expect_equal(parse_gedcom_date("34 JAN 2000"), as.Date(NA_character_))
  expect_equal(parse_gedcom_date("2005"), as.Date("2005-01-01"))
  expect_equal(parse_gedcom_date("2005", FALSE), as.Date("2005-12-31"))
  expect_equal(parse_gedcom_date("JUL 1989"), as.Date("1989-07-01"))
  expect_equal(parse_gedcom_date("JUL 1989", FALSE), as.Date("1989-07-31"))
  expect_equal(parse_gedcom_date("25 MAR 1980"), as.Date("1980-03-25"))
  expect_equal(parse_gedcom_date("25 MAR 1980", FALSE), as.Date("1980-03-25"))
  expect_equal(parse_gedcom_date("FROM 25 MAR 1980 TO 1990", TRUE), as.Date("1980-03-25"))
  expect_equal(parse_gedcom_date("FROM 25 MAR 1980 TO 1990", FALSE), as.Date("1990-12-31"))
})


test_that("Function parse_gedcom_age() @ L120", {
  expect_equal(parse_gedcom_age("16y"), 16)
  expect_equal(parse_gedcom_age("16y 6m"), 16.5)
  expect_equal(parse_gedcom_age("73d"), 73/365)
  expect_equal(parse_gedcom_age("12w"), 12/52)
  expect_equal(parse_gedcom_age("3y 2m 1w 5d"), 3+(2/12)+(1/52)+(5/365))
})

