# Generated by roxytest: do not edit by hand!

# File R/io_export.R: @tests

test_that("Function write_gedcom() @ L37", {
  maximal <- test_path("maximal70.ged")
  maximal <- withr::local_tempfile(lines = fix_maximal_header(maximal), 
                                   fileext = ".ged")
  ged <- read_gedcom(maximal)
  ged@records@prefixes <- c(FAM = "F", INDI = "I", OBJE = "M", REPO = "R", 
                         SNOTE = "N", SOUR = "S", SUBM = "U")
                                 
  expect_error(write_gedcom(ged, "my_family.txt"), 
               regexp = "Output is not being saved as a GEDCOM file")
               
  roundtrip1 <- write_gedcom(ged, "maximal.ged")
  roundtrip2 <- read_gedcom("maximal.ged")
  roundtrip2@records@prefixes <- c(FAM = "F", INDI = "I", OBJE = "M", REPO = "R", 
                         SNOTE = "N", SOUR = "S", SUBM = "U")
  
  expect_identical(
    ged@GEDCOM,
    roundtrip2@GEDCOM
  )
  file.remove("maximal.ged")
})


test_that("Function date_diff() @ L149", {
  expect_equal(date_diff("1900", "2000"), 99, tolerance = 0.01)
  expect_equal(date_diff("1900", "2000", minimise = FALSE), 101, tolerance = 0.01)
  expect_equal(date_diff("800", "2020"), 1219, tolerance = 0.01)
  expect_equal(date_diff("28 JAN 2006", "14 DEC 2008"), 2.877, tolerance = 0.01)
  expect_equal(date_diff("BET JAN 2000 AND 2007", "FROM 2012 TO 8 MAY 2016"), 4, tolerance = 0.01)
  expect_equal(date_diff("BET JAN 2000 AND 2007", "FROM 2012 TO 8 MAY 2016", minimise = FALSE), 16.35, tolerance = 0.01)
  expect_equal(date_diff("ABT 1932", "CAL 2000"), 67, tolerance = 0.01)
})


test_that("Function split_gedcom_values() @ L237", {
  test1 <- c(
  "0 TEMP",
  "1 TAG This is a line\nthen this\nand this\nalso this"
  )
  test2 <- c(
    "0 TEMP",
    "1 TAG A tag",
    "2 QUAY This is a line\nthen this\nand this\nalso this",
    "1 DATE Today"
  )
  
  expect_snapshot_value(split_gedcom_values(test1), "json2")
  expect_snapshot_value(split_gedcom_values(test2), "json2")
})

