# Generated by roxytest: do not edit by hand!

# File R/cls_record_sour.R: @tests

test_that("Function RepositoryCitation() @ L65", {
  expect_snapshot_value(RepositoryCitation()@c_as_ged, "json2")
  expect_snapshot_value(RepositoryCitation(notes = "Local library",
                                                  call_numbers = c("ABC","123"))@c_as_ged, "json2")
})


test_that("Function FactsRecorded() @ L137", {
  expect_error(FactsRecorded("birth"), regexp = "@fact_types is in an invalid format")
  expect_error(FactsRecorded("BIRT "), regexp = "@fact_types is in an invalid format")
  expect_error(FactsRecorded("BIRT,DEAT"), regexp = "@fact_types is in an invalid format")
  expect_error(FactsRecorded("BIRT, DEAT", date_period = "2006"), 
                                    regexp = "@date_period is in an invalid format")
  expect_snapshot_value(FactsRecorded("BIRT")@c_as_ged, "json2")
  expect_snapshot_value(FactsRecorded("BIRT, DEAT",
                                             date_period = "FROM 2007 TO 2010")@c_as_ged, "json2")
  expect_snapshot_value(FactsRecorded("BIRT, DEAT",
                                             date_period = "FROM 2007 TO 2010",
                                             date_phrase = "sometime",
                                             territory = "somewhere")@c_as_ged, "json2")
})

