# Generated by roxytest: do not edit by hand!

# File R/cls_fact_indi.R: @tests

test_that("Function class_event_indi() @ L76", {
  expect_error(class_event_indi("birth", fact_val = "Y"), 
               regexp = "@fact_type has an invalid value")
  expect_error(class_event_indi("BIRT", fact_val = "Yes"), 
               regexp = "@fact_val has an invalid value")
  expect_error(class_event_indi("DEAT", fact_val = "Y", fam_xref = "@12@"), 
               regexp = "@fam_xref has too many elements")
  expect_error(class_event_indi("BIRT", fact_val = "Y", fam_xref = "@12@", adop_parent = "HUSB"), 
               regexp = "@adop_parent has too many elements")
  expect_error(class_event_indi("EVEN", fact_desc = "Fact desc"), 
               regexp = "@fact_val has too few elements")
  expect_error(class_event_indi("ADOP", fact_val = "Y", fam_xref = "@12@", adop_parent = "man"), 
               regexp = "@adop_parent has an invalid value")
  expect_error(class_event_indi("ADOP", fact_val = "Y", adop_parent = "BOTH"), 
               regexp = "@adop_parent requires a @fam_xref")
  expect_error(class_event_indi("ADOP", fact_val = "Y", fam_xref = "@12@", adop_parent_phrase = "both of them"), 
               regexp = "@adop_parent_phrase requires a @adop_parent")
  expect_error(class_event_indi("BIRT", unique_ids = "ABC"), regexp = "@unique_ids is in an invalid format")
  expect_snapshot_value(class_event_indi("BIRT", fact_val = "Y")@as_ged, "json2")
  expect_error(class_event_indi("DEAT", age = "73"), regexp = "@age is in an invalid format")
  expect_snapshot_value(class_event_indi("DEAT", fact_val = "Y")@as_ged, "json2")
  expect_snapshot_value(class_event_indi("DEAT", fact_val = "Y", age_phrase = "old")@as_ged, "json2")
  expect_snapshot_value(class_event_indi("DEAT", fact_val = "Y", age = "73y 4m",
                                        age_phrase = "old")@as_ged, "json2")
  expect_snapshot_value(class_event_indi("ADOP", fact_val = "Y",
                                         fact_desc = "More info on adoption",
                                         fam_xref = "@123@",
                                         adop_parent = "WIFE",
                                         adop_parent_phrase = "Gloria")@as_ged, "json2")
})


test_that("Function class_attr_indi() @ L163", {
  expect_error(class_attr_indi("descr", fact_val = "Tall"), 
               regexp = "@fact_type has an invalid value")
  expect_error(class_attr_indi("DSCR"), 
               regexp = "@fact_val has too few elements")
  expect_error(class_attr_indi("NCHI", fact_val = "2.4"), 
               regexp = "@fact_val is in an invalid format")
  expect_snapshot_value(class_attr_indi("FACT", "Diabetes",
                                   fact_desc = "Medical condition",
                                   date = "26 JUN 2001",
                                   place = class_place("here",
                                                       notes = "place note"),
                                   address = "street, town, city, country",
                                   phone_numbers = "123455",
                                   emails = "things@domain.com",
                                   web_pages = "www.domain.com",
                                   cause = "Chocolate",
                                   locked = TRUE,
                                   date_sort = "2008",
                                   associations = class_association("@I45@", relation_is = "GODP"),
                                   notes = "another note",
                                   note_xrefs = "@N45@",
                                   citations = "@S67@",
                                   unique_ids = "7ddf39aa-42a8-4995-94eb-4392bcc00d28")@as_ged, 
                         "json2")
})

