# Generated by roxytest: do not edit by hand!

# File R/cls_record_media.R: @tests

test_that("Function MediaFile() @ L31", {
  expect_error(MediaFile(location = "media/original.mp3",
                                media_type = "audio/mp3",
                                medium = "CD"),
               regexp = "@medium has an invalid value")
  expect_error(MediaFile(location = "media/original.mp3",
                                media_type = "audio/mp3",
                                medium_phrase = "My CD of things"),
               regexp = "@medium_phrase requires a @medium")
  expect_error(MediaFile(location = "media/original.mp3",
                                media_type = "audio/mp3",
                                medium = "OTHER"),
               regexp = "A @medium_phrase must be given if @medium is 'OTHER'")
  expect_snapshot_value(MediaFile(location = "media/original.mp3",
                                         title = "My audio",
                                         media_type = "audio/mp3",
                                         medium = "ELECTRONIC",
                                         medium_phrase = "My CD of things",
                                         media_alt = c("audio/ogg" = "media/derived.oga",
                                                       "text/vtt" = "media/transcript.vtt"))@GEDCOM,
                         "json2")
})


test_that("Function MediaRecord() @ L114", {
  fls <- list(MediaFile(location = "media/original.mp3",
                                         title = "My audio",
                                         media_type = "audio/mp3",
                                         medium = "ELECTRONIC",
                                         medium_phrase = "My CD of things",
                                         media_alt = c("audio/ogg" = "media/derived.oga",
                                                       "text/vtt" = "media/transcript.vtt")),
              MediaFile(location = "media/speech.mp3",
                               media_type = "audio/mp3")
             )
             
  expect_snapshot_value(MediaRecord("@M548@", files = fls,
                                           locked = TRUE,
                                           notes = "Very loud")@GEDCOM, "json2")
})

