# Generated by roxytest: do not edit by hand!

# File R/fn_df.R: @tests

test_that("Function df_fam() @ L106", {
  fam_df <- df_fam(test_ged())
  expect_equal(nrow(fam_df), 3)
  expect_equal(fam_df$husb_xref[1], "@I2@")
  expect_equal(fam_df$wife_xref[2], "@I4@")
  expect_equal(fam_df$unique_ids[3], "f511d543-43c2-4642-b7dd-31c1a2a6bbc2")
  expect_equal(fam_df$user_ids[3], "My ID=1234")
  expect_equal(fam_df$ext_ids[3], "http://www.website.com/page1")
})


test_that("Function df_indi() @ L72", {
  indi_df <- df_indi(test_ged())
  expect_equal(nrow(indi_df), 6)
  expect_equal(indi_df$name[2], "Father /Bloggs/")
  expect_equal(indi_df$sex[3], "F")
  expect_equal(indi_df$birth_date[1], "20 MAR 1967")
  expect_equal(indi_df$fam_as_child[5], "@F2@")
  expect_equal(indi_df$fam_as_child[6], "@F2@")
})


test_that("Function df_indi_facts() @ L227", {
  fact_df <- df_indi_facts(test_ged(), "@I1@")
  expect_equal(fact_df$type[1], "Birth")
  expect_equal(fact_df$type[4], "Other attribute")
  expect_equal(fact_df$val[2], "5 ft 10, brown hair, brown eyes")
  expect_equal(fact_df$desc[4], "Disability")
  expect_equal(fact_df$date[3], "8 APR 2018")
  expect_equal(fact_df$place[1], "California, USA")
  expect_equal(fact_df$age[3], "51y")
})


test_that("Function df_fam_facts() @ L263", {
  fact_df <- df_fam_facts(test_ged(), "@F1@")
  expect_equal(fact_df$type[1], "Marriage")
  expect_equal(fact_df$date[1], "MAR 1965")
  expect_equal(fact_df$place[1], "London, England")
  expect_equal(fact_df$husb_age[1], "28y")
  expect_equal(fact_df$wife_age[1], "25y")
})

