# Generated by roxytest: do not edit by hand!

# File R/cls_gedcom.R: @tests

test_that("Function GedcomS7() @ L281", {
  maximal <- test_path("maximal70.ged")
  maximal <- withr::local_tempfile(lines = fix_maximal_header(maximal), 
                                   fileext = ".ged")
  ged_raw <- readLines(maximal)
  ged_parsed <- read_gedcom(maximal)
  ged_parsed@xref_prefixes <- c(fam = "F", indi = "I", media = "M", repo = "R", 
                                 note = "N", sour = "S", subm = "U")
  ged_raw2 <- ged_parsed@c_as_ged
  
  expect_equal(ged_raw, ged_raw2)
})

