# Generated by roxytest: do not edit by hand!

# File R/cls_association.R: @tests

test_that("Function class_association() @ L22", {
  expect_snapshot_value(class_association(relation_is = "FATH")@as_ged, "json2")
  expect_error(class_association(indi_phrase = "someone", relation_is = "CHILD"),
               regexp = "@relation_is has an invalid value")
  expect_snapshot_value(class_association(indi_phrase = "someone",
                                          relation_is = "FATH")@as_ged, "json2")
  expect_snapshot_value(class_association(indi_xref = "@SME@", indi_phrase = "someone",
                                          relation_is = "FATH", relation_phrase = "step-father",
                                          note_xrefs = c("@352@","@564@"),
                                          notes = "This is a note",
                                          citations = class_citation("@S45@",
                                                                     where = "Page 2"))@as_ged, "json2")
})

