# Generated by roxytest: do not edit by hand!

# File R/fn_add_rm.R: @tests

test_that("Function add_parents() @ L79", {
  ged <- new_gedcom()
  
  ged_no_parents <- push_record(ged, IndividualRecord()) |> 
                    suppressMessages()
  ged_with_parents <- add_parents(ged_no_parents, "@I1@") |> 
                    suppressMessages()
  expect_true("1 SEX M" %in% ged_with_parents@records@RAW@INDI[["@I2@"]])
  expect_true("1 SEX F" %in% ged_with_parents@records@RAW@INDI[["@I3@"]])
  expect_true("1 CHIL @I1@" %in% ged_with_parents@records@RAW@FAM[["@F1@"]])
  expect_true("1 HUSB @I2@" %in% ged_with_parents@records@RAW@FAM[["@F1@"]])
  expect_true("1 WIFE @I3@" %in% ged_with_parents@records@RAW@FAM[["@F1@"]])
  
  ged_with_parents <- add_parents(ged_no_parents, "@I1@", inc_sex = FALSE) |> 
                    suppressMessages()
  expect_false("1 SEX M" %in% ged_with_parents@records@RAW@INDI[["@I2@"]])
  expect_false("1 SEX F" %in% ged_with_parents@records@RAW@INDI[["@I3@"]])
  
  ged_with_parents <- add_parents(ged_no_parents, "@I1@",
                                  fath_name = "Joe /Bloggs/",
                                  moth_name = "Jess /Bloggs/") |> 
                    suppressMessages()
  expect_true("1 NAME Joe /Bloggs/" %in% ged_with_parents@records@RAW@INDI[["@I2@"]])
  expect_true("1 NAME Jess /Bloggs/" %in% ged_with_parents@records@RAW@INDI[["@I3@"]])
  
  ged_with_parents2 <- add_parents(ged_with_parents, "@I1@") |> 
                    suppressMessages()
  expect_equal(ged_with_parents@GEDCOM, ged_with_parents2@GEDCOM)
  expect_warning(add_parents(ged_with_parents, "@I1@", fath_name = "Me"),
                 regexp = "^Father name not used")
  expect_warning(add_parents(ged_with_parents, "@I1@", moth_name = "Me"),
                 regexp = "^Mother name not used")
  
  ged_one_parent_f <- suppressMessages(
    ged |> 
      push_record(IndividualRecord()) |>
      push_record(IndividualRecord(sex = "M")) |> 
      push_record(FamilyRecord(chil_xrefs = "@I1@", husb_xref = "@I2@"))
  )
  ged_with_parents <- add_parents(ged_one_parent_f, "@I1@") |> 
                    suppressMessages()
  expect_true("1 SEX M" %in% ged_with_parents@records@RAW@INDI[["@I2@"]])
  expect_true("1 SEX F" %in% ged_with_parents@records@RAW@INDI[["@I3@"]])
  expect_true("1 CHIL @I1@" %in% ged_with_parents@records@RAW@FAM[["@F1@"]])
  expect_true("1 HUSB @I2@" %in% ged_with_parents@records@RAW@FAM[["@F1@"]])
  expect_true("1 WIFE @I3@" %in% ged_with_parents@records@RAW@FAM[["@F1@"]])
  
  ged_one_parent_m <- suppressMessages(
    ged |> 
      push_record(IndividualRecord()) |>
      push_record(IndividualRecord(sex = "F")) |> 
      push_record(FamilyRecord(chil_xrefs = "@I1@", wife_xref = "@I2@"))
  )
  ged_with_parents <- add_parents(ged_one_parent_m, "@I1@") |> 
                    suppressMessages()
  expect_true("1 SEX F" %in% ged_with_parents@records@RAW@INDI[["@I2@"]])
  expect_true("1 SEX M" %in% ged_with_parents@records@RAW@INDI[["@I3@"]])
  expect_true("1 CHIL @I1@" %in% ged_with_parents@records@RAW@FAM[["@F1@"]])
  expect_true("1 WIFE @I2@" %in% ged_with_parents@records@RAW@FAM[["@F1@"]])
  expect_true("1 HUSB @I3@" %in% ged_with_parents@records@RAW@FAM[["@F1@"]])
})


test_that("Function add_spouse() @ L195", {
  ged <- new_gedcom()
  
  ged_no_spouse <- push_record(ged, IndividualRecord()) |> 
                    suppressMessages()
  ged_with_spouse <- add_spouse(ged_no_spouse, "@I1@") |> 
                    suppressMessages()
  
  expect_true("1 SEX U" %in% ged_with_spouse@records@RAW@INDI[["@I2@"]])
  expect_true("1 HUSB @I1@" %in% ged_with_spouse@records@RAW@FAM[["@F1@"]])
  expect_true("1 WIFE @I2@" %in% ged_with_spouse@records@RAW@FAM[["@F1@"]])
  
  ged_with_spouse <- add_spouse(ged_no_spouse, "@I1@",
                                spou_name = "Joe /Bloggs/") |> 
                    suppressMessages()
  
  expect_true("1 NAME Joe /Bloggs/" %in% ged_with_spouse@records@RAW@INDI[["@I2@"]])
  
  ged_no_spouse_fam <- suppressMessages(
    ged |> 
      push_record(IndividualRecord()) |> 
      push_record(FamilyRecord(husb_xref = "@I1@"))
  )
  ged_with_spouse_fam_new <- add_spouse(ged_no_spouse_fam, "@I1@") |> 
                    suppressMessages()
  ged_with_spouse_fam <- add_spouse(ged_no_spouse_fam, "@I1@", fam_xref = "@F1@") |> 
                    suppressMessages()
  
  expect_equal(length(ged_with_spouse_fam_new@records@RAW@FAM), 2)
  expect_equal(length(ged_with_spouse_fam@records@RAW@FAM), 1)
  expect_true("1 HUSB @I1@" %in% ged_with_spouse_fam_new@records@RAW@FAM[["@F1@"]])
  expect_true("1 HUSB @I1@" %in% ged_with_spouse_fam_new@records@RAW@FAM[["@F2@"]])
  
  expect_false("1 WIFE @I2@" %in% ged_with_spouse_fam_new@records@RAW@FAM[["@F1@"]])
  expect_true("1 WIFE @I2@" %in% ged_with_spouse_fam_new@records@RAW@FAM[["@F2@"]])
  
  expect_true("1 HUSB @I1@" %in% ged_with_spouse_fam@records@RAW@FAM[["@F1@"]])
  expect_true("1 WIFE @I2@" %in% ged_with_spouse_fam@records@RAW@FAM[["@F1@"]])
})


test_that("Function rm_xref_ptrs() @ L389", {
  lines <- readLines(test_path("maximal70.ged"))
  lines1 <- lines[391:399]
  void_lines <- rm_xref_ptrs(lines1, "@S1@", TRUE)
  expect_equal(parse_line_value(void_lines)[6], "@VOID@")
  expect_equal(parse_line_value(void_lines)[8], "@VOID@")
  expect_length(rm_xref_ptrs(lines1, "@S1@", FALSE), 5)
  void_lines <- rm_xref_ptrs(lines1, "@N1@", TRUE)
  expect_equal(parse_line_value(void_lines)[5], "@VOID@")
  expect_length(rm_xref_ptrs(lines1, "@N1@", FALSE), 8)
})

