# Generated by roxytest: do not edit by hand!

# File R/cls_personal_name.R: @tests

test_that("Function class_name_pieces() @ L17", {
  expect_snapshot_value(class_name_pieces(prefix = "Mr",
                                          given = "Joe",
                                          nickname = c("J","Jock"),
                                          surname_prefix = "Mc",
                                          surname = "Bloggs",
                                          suffix = "Jr")@as_ged, "json2")
})


test_that("Function class_personal_name_tran() @ L67", {
  expect_snapshot_value(class_personal_name_tran("Joe /Bloggs/",
                                                 language = "en")@as_ged, "json2")
  expect_snapshot_value(class_personal_name_tran("Joe /Bloggs/",
                                                 language = "en",
                                                 name_pieces = class_name_pieces(nickname = "JJ"))@as_ged, "json2")
})


test_that("Function class_personal_name() @ L116", {
  expect_error(class_personal_name("Joe /Bloggs/", name_type = "birth"),
               regexp = "@name_type has an invalid value")
  expect_error(class_personal_name("Joe /Bloggs/", type_phrase = "After 2012"),
               regexp = "@type_phrase requires a @name_type")
  expect_snapshot_value(class_personal_name("Joe /Bloggs/",
                                            name_type = "OTHER",
                                            type_phrase = "Circus",
                                            name_pieces = class_name_pieces(nickname = "JJ"),
                                            name_translations = class_personal_name_tran("Joey /Bloggoni/",
                                                                                         language = "it"),
                                            notes = "This is a note",
                                            note_xrefs = c("@IUY@","@733@"),
                                            citations = c("@S1@","@S3@","@S7@"))@as_ged, "json2")
})

