# Generated by roxytest: do not edit by hand!

# File R/cls_record_note.R: @tests

test_that("Function NoteRecord() @ L14", {
  expect_snapshot_value(NoteRecord("@N4@",
                                          text = "The note goes something like this",
                                          language = "en")@c_as_ged, "json2")
})

