# Generated by roxytest: do not edit by hand!

# File R/cls_media_file.R: @tests

test_that("Function class_media_file() @ L26", {
  expect_error(class_media_file(location = "media/original.mp3",
                                media_type = "audio/mp3",
                                medium = "CD"),
               regexp = "@medium has an invalid value")
  expect_error(class_media_file(location = "media/original.mp3",
                                media_type = "audio/mp3",
                                medium_phrase = "My CD of things"),
               regexp = "@medium_phrase requires a @medium")
  expect_snapshot_value(class_media_file(location = "media/original.mp3",
                                         title = "My audio",
                                         media_type = "audio/mp3",
                                         medium = "ELECTRONIC",
                                         medium_phrase = "My CD of things",
                                         media_alt = c("audio/ogg" = "media/derived.oga",
                                                       "text/vtt" = "media/transcript.vtt"))@as_ged,
                         "json2")
})

