# Generated by roxytest: do not edit by hand!

# File R/cls_repository_citation.R: @tests

test_that("Function class_repository_citation() @ L15", {
  expect_snapshot_value(class_repository_citation()@as_ged, "json2")
  expect_snapshot_value(class_repository_citation(notes = "Local library",
                                                  call_numbers = c("ABC","123"))@as_ged, "json2")
})

