# Generated by roxytest: do not edit by hand!

# File R/cls_personal_name.R: @tests

test_that("Function PersonalNamePieces() @ L22", {
  expect_snapshot_value(PersonalNamePieces(prefix = "Mr",
                                          given = "Joe",
                                          nickname = c("J","Jock"),
                                          surname_prefix = "Mc",
                                          surname = "Bloggs",
                                          suffix = "Jr")@c_as_ged, "json2")
})


test_that("Function PersonalNameTran() @ L79", {
  expect_snapshot_value(PersonalNameTran("Joe /Bloggs/",
                                                 language = "en")@c_as_ged, "json2")
  expect_snapshot_value(PersonalNameTran("Joe /Bloggs/",
                                                 language = "en",
                                                 name_pieces = PersonalNamePieces(nickname = "JJ"))@c_as_ged, "json2")
})


test_that("Function PersonalName() @ L133", {
  expect_error(PersonalName("Joe /Bloggs/", name_type = "birth"),
               regexp = "@name_type has an invalid value")
  expect_error(PersonalName("Joe /Bloggs/", type_phrase = "After 2012"),
               regexp = "@type_phrase requires a @name_type")
  expect_snapshot_value(PersonalName("Joe /Bloggs/",
                                            name_type = "OTHER",
                                            type_phrase = "Circus",
                                            name_pieces = PersonalNamePieces(nickname = "JJ"),
                                            name_translations = PersonalNameTran("Joey /Bloggoni/",
                                                                                         language = "it"),
                                            notes = "This is a note",
                                            note_xrefs = c("@IUY@","@733@"),
                                            citations = c("@S1@","@S3@","@S7@"))@c_as_ged, "json2")
})

