# Generated by roxytest: do not edit by hand!

# File R/cls_record.R: @tests

test_that("Function Record() @ L21", {
  maximal <- test_path("maximal70.ged")
  maximal <- withr::local_tempfile(lines = fix_maximal_records(maximal), 
                                   fileext = ".ged")
  ged <- read_gedcom(maximal)
  
  for(rec_type in names(ged@records@prefixes)){
    xrefs <- ged@records@XREFS[[rec_type]]
    
    for(xref in xrefs){
      rec_raw <- S7::prop(ged@records@RAW, rec_type)[[xref]]
      
      # Remove extension tags
      rec_raw <- rec_raw[grepl(anchor_it(reg_tag()), parse_line_tag(rec_raw))]
      rec_parsed <- suppressWarnings(pull_record(ged, xref))
      
      expect_equal(rec_parsed@GEDCOM, rec_raw)
    }
  }
})

