# Generated by roxytest: do not edit by hand!

# File R/cls_note.R: @tests

test_that("Function Note() @ L42", {
  expect_error(Note(), regexp = "@text has too few elements")
  expect_error(Note(letters[1:2]), regexp = "@text has too many elements")
  expect_error(Note("test", translations = TranslationText("Ole")),
               regexp = "Each @translation requires a @language or @media_type")
  expect_snapshot_value(Note("test")@GEDCOM, "json2")
  expect_snapshot_value(Note("test", language = "en")@GEDCOM, "json2")
  expect_snapshot_value(Note("test", 
                                   language = "en",
                                   translations = TranslationText("test",
                                                                    language = "en"))@GEDCOM, "json2")
  expect_snapshot_value(Note("test", 
                                   language = "en",
                                   translations = list(TranslationText("test",
                                                                    language = "en"),
                                                   TranslationText("test2",
                                                                    language = "en")))@GEDCOM, "json2")
  expect_snapshot_value(Note("test", 
                                   citations = SourceCitation("@S1@", 
                                                              notes = Note("note text 2", 
                                                                                 citations = SourceCitation("@S4@"))))@GEDCOM, 
                       "json2")
  expect_error(Note("test", 
                          language = "en",
                          translations = Address("street")),
               regexp = "gedcomS7::Address cannot be converted to class TranslationText")
  expect_error(Note("test", 
                          language = "en",
                          translations = list(TranslationText("test",
                                                                language = "en"),
                                          Address("street"))),
               regexp = "gedcomS7::Address cannot be converted to class TranslationText")
})

