# Generated by roxytest: do not edit by hand!

# File R/cls_citation.R: @tests

test_that("Function class_citation() @ L42", {
  expect_snapshot_value(class_citation()@as_ged, "json2")
  expect_error(class_citation("@1@",
                              event_phrase = "phrase"),
               regexp = "@event_phrase requires a @event_types")
  expect_error(class_citation("@1@",
                              role = "HUSB"),
               regexp = "@role requires a @event_types")
  expect_error(class_citation("@1@",
                              event_types = "BIRT", role_phrase = "phrase"),
               regexp = "@role_phrase requires a @role")
  expect_error(class_citation("@1@",
                              certainty = "4"),
               regexp = "@certainty has an invalid value")
  expect_error(class_citation("@1@",
                              notes = ""),
               regexp = "@notes is in an invalid format")
  expect_snapshot_value(class_citation("@1@",
                                       where = "page 2",
                                       date = "2 JUN 2006",
                                       source_text = c("verbatim","text"),
                                       event_types = "BIRT, MARR, DEAT",
                                       event_phrase = "and others",
                                       role = "HUSB",
                                       role_phrase = "phrase",
                                       certainty = "3",
                                       media_links = class_media_link("@34E@"),
                                       note_xrefs = c("@WER@",
                                                     "@4334@"),
                                       notes = c("these are","some notes"))@as_ged, "json2")
})

