# Generated by roxytest: do not edit by hand!

# File R/fn_push_pull.R: @tests

test_that("Function pull_record() @ L34", {
  expect_error(pull_record(new_gedcom(), "@I1@"),
               regexp = "^The xref is not in the GEDCOM")
  
  ged <- new_gedcom() |> 
           push_record(IndividualRecord(locked = TRUE)) |> 
           suppressMessages()
  expect_warning(pull_record(ged, "@I1@"),
                 regexp = "^The record is locked")
                 
  ged <- new_gedcom() |> 
           push_record(IndividualRecord(
              facts = IndividualEvent("BIRT", locked = TRUE))) |> 
           suppressMessages()
  expect_warning(pull_record(ged, "@I1@"),
                 regexp = "^The following facts are locked")
                 
  ged <- new_gedcom() |> 
           push_record(IndividualRecord(sex = "M")) |> 
           suppressMessages()
  ged@indi[[1]] <- c(ged@indi[[1]], "1 _FRE Wow", "2 _ERR No")
  expect_warning(pull_record(ged, "@I1@"),
                 regexp = "The following lines could not be parsed.+Wow.+No")
})


test_that("Function push_record() @ L131", {
  ged <- new_gedcom()
  ged@update_change_dates <- TRUE
  ged@add_creation_dates <- TRUE
  expect_message(ged <- push_record(ged, IndividualRecord()),
                 regexp = "New Individual record added with xref @I1@")
  expect_true("1 CHAN" %in% ged@indi[[1]])
  expect_true("1 CREA" %in% ged@indi[[1]])
  
  ged <- new_gedcom()
  
  expect_error(push_record(ged, FamilyRecord(chil_xrefs = "@I1@")),
               regexp = "^The following xrefs were not found in the GEDCOM object: @I1@")
  expect_error(push_record(ged, IndividualRecord(fam_links_spou = "@F1@",
                                                 media_links = "@O1@")),
               regexp = "^The following xrefs were not found in the GEDCOM object: @F1@, @O1@")
               
  suppressMessages({
    ged <- push_record(ged, FamilyRecord())
    ged <- push_record(ged, FamilyRecord())
    ged <- push_record(ged, IndividualRecord(fam_links_spou = "@F2@"))
    ged <- push_record(ged, IndividualRecord(fam_links_chil = "@F1@"))
  })
  
  expect_true("1 HUSB @I1@" %in% ged@fam[["@F2@"]])
  expect_true("1 CHIL @I2@" %in% ged@fam[["@F1@"]])
  
  suppressMessages({
    rec_F1 <- pull_record(ged, "@F1@")
    rec_F1@chil_xrefs <- "@I1@"
    ged <- push_record(ged, rec_F1)
    
    rec_F2 <- pull_record(ged, "@F2@")
    rec_F2@husb_xref <- "@I2@"
    ged <- push_record(ged, rec_F2)
  })
  
  expect_true("1 FAMC @F1@" %in% ged@indi[["@I1@"]])
  expect_true("1 FAMS @F2@" %in% ged@indi[["@I2@"]])
  expect_false("1 FAMC @F1@" %in% ged@indi[["@I2@"]])
  expect_false("1 FAMS @F2@" %in% ged@indi[["@I1@"]])
  expect_false("1 CHIL @I2@" %in% ged@fam[["@F1@"]])
  expect_false("1 HUSB @I1@" %in% ged@fam[["@F2@"]])
})

