# Generated by roxytest: do not edit by hand!

# File R/cls_fact_fam.R: @tests

test_that("Function FamilyEvent() @ L75", {
  expect_error(FamilyEvent("marr", fact_val = "Y"), 
               regexp = "This is not a valid @fact_type for this event")
  expect_error(FamilyEvent("MARR", fact_val = "Yes"), 
               regexp = "Only a @fact_val of 'Y' is permitted for this event")
  expect_error(FamilyEvent("EVEN", fact_desc = "Fact desc"), 
               regexp = "A @fact_val is required for this fact")       
  expect_error(FamilyEvent("DIV", fact_val = "Y", husb_age = "73"), regexp = "@husb_age is in an invalid format")
  expect_snapshot_value(FamilyEvent("DIV", fact_val = "Y")@GEDCOM, "json2")
  expect_snapshot_value(FamilyEvent("DIV", fact_val = "Y", wife_age_phrase = "old")@GEDCOM, "json2")
  expect_snapshot_value(FamilyEvent("DIV", fact_val = "Y", husb_age = "73y 4m",
                                        wife_age = "60y")@GEDCOM, "json2")
})


test_that("Function FamilyAttribute() @ L98", {
  expect_error(FamilyAttribute("residence", fact_val = "Earth"), 
               regexp = "This is not a valid @fact_type for this attribute")
  expect_error(FamilyAttribute("RESI", fact_val = ""), 
               regexp = "@fact_val has too few characters")   
  expect_error(FamilyAttribute("FACT"), regexp = "A @fact_val is required for this fact")
  expect_error(FamilyAttribute("NCHI", 3.2), regexp = "Number of children/marriages must be a whole number")
  expect_error(FamilyAttribute("NCHI", fact_val = "3", date = ""),
               regexp = "A blank @date requires a @date_phrase")
})

