# Generated by roxytest: do not edit by hand!

# File R/cls_gedcom.R: @tests

test_that("Function class_gedcomS7() @ L228", {
  ged_raw <- readLines(system.file("extdata", "maximal70.ged", package = "gedcomS7")) |> 
              remove_unsupported_structures_for_tests()
  ged_parsed <- read_gedcom(system.file("extdata", "maximal70.ged", package = "gedcomS7"))
  ged_parsed@xref_prefixes <- c(fam = "F", indi = "I", media = "M", repo = "R", 
                                 note = "N", sour = "S", subm = "U")
  ged_raw2 <- ged_parsed@as_ged
  
  expect_equal(ged_raw, ged_raw2)
})

