# Generated by roxytest: do not edit by hand!

# File R/cls_address.R: @tests

test_that("Function class_address() @ L28", {
  expect_error(class_address(), "@full has too few elements")
  expect_error(class_address(""), "@full has too few characters")
  expect_snapshot_value(class_address("street\ncity\nstate")@as_ged, "json2")
  expect_snapshot_value(class_address("street\ncity\nstate",
                                      city = "this city")@as_ged, "json2")
  expect_snapshot_value(class_address("street\ncity\nstate",
                                      state = "this state")@as_ged, "json2")
  expect_snapshot_value(class_address("street\ncity\nstate",
                                      country = "this country")@as_ged, "json2")
  expect_snapshot_value(class_address("street\ncity\nstate",
                                      city = "this city",
                                      state = "this state",
                                      country = "this country")@as_ged, "json2")
  expect_snapshot_value(class_address("street\ncity\nstate",
                                      city = "this city",
                                      state = "this state",
                                      country = "this country",
                                      postal_code = "81309")@as_ged, "json2")
})

