# Generated by roxytest: do not edit by hand!

# File R/cls_personal_name.R: @tests

test_that("Function PersonalNamePieces() @ L22", {
  expect_snapshot_value(PersonalNamePieces(prefix = "Mr",
                                          given = "Joe",
                                          nickname = c("J","Jock"),
                                          surname_prefix = "Mc",
                                          surname = "Bloggs",
                                          suffix = "Jr")@GEDCOM, "json2")
})


test_that("Function PersonalNameTran() @ L80", {
  expect_snapshot_value(PersonalNameTran("Joe /Bloggs/",
                                                 language = "en")@GEDCOM, "json2")
  expect_snapshot_value(PersonalNameTran("Joe /Bloggs/",
                                                 language = "en",
                                                 name_pieces = PersonalNamePieces(nickname = "JJ"))@GEDCOM, "json2")
})


test_that("Function PersonalName() @ L142", {
  expect_warning(PersonalName("Joe Bloggs"),
                 regexp = "Did you forget to enclose the surname in forward slashes")
  expect_error(PersonalName("Joe /Bloggs/", name_type = "birth"),
               regexp = "@name_type has an invalid value")
  expect_error(PersonalName("Joe /Bloggs/", type_phrase = "After 2012"),
               regexp = "@type_phrase requires a @name_type")
  expect_error(PersonalName("Joe /Bloggs/", name_type = "OTHER"),
               regexp = "A @type_phrase must be given if @name_type is 'OTHER'")
  expect_snapshot_value(PersonalName("Joe /Bloggs/",
                                            name_type = "OTHER",
                                            type_phrase = "Circus",
                                            name_pieces = PersonalNamePieces(nickname = "JJ"),
                                            name_translations = PersonalNameTran("Joey /Bloggoni/",
                                                                                         language = "it"),
                                            notes = "This is a note",
                                            note_xrefs = c("@IUY@","@733@"),
                                            citations = c("@S1@","@S3@","@S7@"))@GEDCOM, "json2")
})

