# Generated by roxytest: do not edit by hand!

# File R/cls_record_fam.R: @tests

test_that("Function FamilyRecord() @ L34", {
  fct <- list(FamilyEvent("MARR", husb_age = "22y", wife_age = "28y 6m",
                             date = "22 AUG 1907", place = "Church"))
  nevent <- list(NonEvent("DIV"))
  expect_snapshot_value(FamilyRecord(xref = "@F2@",
                                         facts = fct, non_events = nevent,
                                         husb_xref = "@I8@", wife_xref = "@I9@",
                                         chil_xrefs = c("@I98@", Eldest = "@I67@"),
                                         locked = TRUE,
                                         citations = c("@S34@","@S65@"))@c_as_ged, "json2")
  expect_error(FamilyRecord("REF"), regexp = "@xref is in an invalid format")
  expect_error(FamilyRecord(unique_ids = letters), regexp = "@unique_ids is in an invalid format")
  expect_error(FamilyRecord(ext_ids = LETTERS), regexp = "@ext_ids has too few elements")
  expect_snapshot_value(FamilyRecord("@1@",
                                     unique_ids = "a95b5007-2ad2-4bac-81b0-7184243c4512",
                                     ext_ids = stats::setNames(letters, LETTERS)[1:5],
                                     user_ids = month.abb[1:6])@c_ids_as_ged, "json2")
})

