# Generated by roxytest: do not edit by hand!

# File R/cls_fact.R: @tests

test_that("Function class_fact() @ L34", {
  expect_error(class_fact("FACT"), regexp = "@fact_desc has too few elements")
  expect_error(class_fact("BIRT", unique_ids = "ABC"), regexp = "@unique_ids is in an invalid format")
  expect_snapshot_value(class_fact("BIRT", fact_val = "Y")@.fact_detail_as_ged, "json2")
  expect_warning(class_fact("BIRT")@.fact_detail_as_ged, regexp = "You are asserting")
  expect_snapshot_value(class_fact("FACT", "Diabetes",
                                   fact_desc = "Medical condition",
                                   date = "26 JUN 2001",
                                   place = class_place("here",
                                                       notes = "place note"),
                                   address = "street, town, city, country",
                                   phone_numbers = "123455",
                                   emails = "things@domain.com",
                                   web_pages = "www.domain.com",
                                   cause = "Chocolate",
                                   locked = TRUE,
                                   date_sort = "2008",
                                   associations = class_association("@I45@", relation_is = "GODP"),
                                   notes = "another note",
                                   note_xrefs = "@N45@",
                                   citations = "@S67@",
                                   unique_ids = "7ddf39aa-42a8-4995-94eb-4392bcc00d28")@.fact_detail_as_ged, 
                         "json2")
})

