# Generated by roxytest: do not edit by hand!

# File R/cls_record.R: @tests

test_that("Function class_record() @ L18", {
  expect_error(class_record(), regexp = "@xref has too few elements")
  expect_error(class_record("REF"), regexp = "@xref is in an invalid format")
  expect_error(class_record("@1@", unique_ids = letters), regexp = "@unique_ids is in an invalid format")
  expect_error(class_record("@1@", ext_ids = LETTERS), regexp = "@ext_ids names has too few elements")
  expect_snapshot_value(class_record("@1@",
                                     unique_ids = "a95b5007-2ad2-4bac-81b0-7184243c4512",
                                     ext_ids = setNames(letters, LETTERS)[1:5],
                                     user_ids = month.abb[1:6])@ids, "json2")
})

