# Generated by roxytest: do not edit by hand!

# File R/cls_non_event.R: @tests

test_that("Function class_non_event() @ L21", {
  expect_error(class_non_event("death"), regexp = "@event_type has an invalid value")
  expect_error(class_non_event("DEAT", date_phrase = "Before the olympics"), 
               regexp = "@date_phrase requires a @date_period")
  expect_error(class_non_event("DEAT", date_period = "JAN 1984"), 
               regexp = "@date_period is in an invalid format")
  expect_snapshot_value(class_non_event("IMMI", 
                                        date_period = class_date_period("16 JUN 1980","1994"),
                                        date_phrase = "While parents alive",
                                        notes = "Note 1",
                                        citations = "@S98@")@as_ged, "json2")
})

