# Generated by roxytest: do not edit by hand!

# File R/cls_gedcom.R: @tests

test_that("Function GedcomS7() @ L273", {
  maximal <- test_path("maximal70.ged")
  maximal <- withr::local_tempfile(lines = fix_maximal_header(maximal), 
                                   fileext = ".ged")
  ged_raw <- readLines(maximal)
  ged_parsed <- read_gedcom(maximal)
  ged_parsed@records@prefixes <- c(FAM = "F", INDI = "I", OBJE = "M", REPO = "R", 
                                   SNOTE = "N", SOUR = "S", SUBM = "U")
  ged_raw2 <- ged_parsed@GEDCOM
  
  expect_equal(ged_raw, ged_raw2)
})

